test-lib: sync with git-test-lib project
Signed-off-by: Jiang Xin <zhiyou.jx@alibaba-inc.com>

diff --git a/test/lib/helper/test-tool b/test/lib/helper/test-tool
--- a/test/lib/helper/test-tool
+++ b/test/lib/helper/test-tool
@@ -1,11 +1,17 @@
 #!/bin/sh
 
-: "${PYTHON_PATH:=$(which python)}"
-
 if test -z "$PYTHON_PATH"
 then
-	echo >&2 "ERROR: python not installed, cannot run test-tool."
-	exit 1
+	if type python3 >/dev/null 2>&1
+	then
+		PYTHON_PATH="$(which python3)"
+	elif type python >/dev/null 2>&1
+	then
+		PYTHON_PATH="$(which python)"
+	else
+		echo >&2 "ERROR: python not installed, cannot run test-tool."
+		exit 1
+	fi
 fi
 
 helper_dir=$(cd "$(dirname $0)" && pwd)
